apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saqr-platform-cluster

resources:
  - ../../base

commonLabels:
  saqr.io/package-profile: per-cluster-entity-ring
  saqr.io/topology-pattern: per_cluster
  saqr.io/boundary-scope: cluster

patchesStrategicMerge:
  - configmap.patch.yaml
  - ingress.patch.yaml
