apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saqr-platform-tenant

resources:
  - ../../base

commonLabels:
  saqr.io/package-profile: single-tenant-sovereign-cloud
  saqr.io/topology-pattern: single_tenant
  saqr.io/boundary-scope: tenant

patchesStrategicMerge:
  - configmap.patch.yaml
  - ingress.patch.yaml
