apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saqr-platform
spec:
  rules:
    - host: saqr.country.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saqr-shield-ui
                port:
                  number: 80
    - host: api.saqr.country.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saqr-api
                port:
                  number: 3001
