apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saqr-platform-country

resources:
  - ../../base

commonLabels:
  saqr.io/package-profile: per-country-sovereign-cloud
  saqr.io/topology-pattern: per_country
  saqr.io/boundary-scope: country

patchesStrategicMerge:
  - configmap.patch.yaml
  - ingress.patch.yaml
