apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.template.yaml
  - secret.template.yaml
  - deployments.yaml
  - services.yaml
  - ingress.template.yaml

