apiVersion: v1
kind: Secret
metadata:
  name: saqr-platform-secrets
  namespace: saqr-platform
type: Opaque
stringData:
  JWT_SECRET: "replace-in-delivery"
  SHADOW_DB_HOST: "replace-by-delivery-team"
  SHADOW_DB_USER: "replace-by-delivery-team"
  SHADOW_DB_PASSWORD: "replace-by-delivery-team"
  KAFKA_BOOTSTRAP_SERVERS: "replace-by-delivery-team"
  CV_VMS_HOST: "replace-by-delivery-team"
  CV_VMS_USERNAME: "replace-by-delivery-team"
  CV_VMS_PASSWORD: "replace-by-delivery-team"
  SAQR_UI_STATIC_BEARER_TOKEN: ""

