apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saqr-platform-onprem

resources:
  - ../../base

commonLabels:
  saqr.io/package-profile: client-on-premises
  saqr.io/topology-pattern: on_premises
  saqr.io/boundary-scope: premises

patchesStrategicMerge:
  - configmap.patch.yaml
  - ingress.patch.yaml
